###
POST http://localhost:3002/event/add HTTP/1.1
Content-Type: application/json

{
  "title":"new Event",
  "time":"13:30",
  "duration":"40",
  "subject":"Something",
  "date":"2020-06-12T00:00:00Z"
}

###

POST http://localhost:3002/slot/list HTTP/1.1
Content-Type: application/json

{
  "duration":"30",
  "date":"2020-06-12T00:00:00Z"
}

###

POST http://localhost:3002/event/list HTTP/1.1
Content-Type: application/json

{
  "start_date":"2020-01-09T00:00:00Z",
  "end_date":"2020-12-10T00:00:00Z"
}